# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - helm
      - terraform


resources:
- repo: self


variables:
  # Container registry service connection established during pipeline creation
  imageRepository: 'application'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          containerRegistry: 'ACR'
          repository: '$(imageRepository)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: $(Build.BuildId)

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
      - task: HelmInstaller@0
        inputs:
          helmVersion: '3.6.0'
          installKubectl: true

      - script: |
          helm registry login $(ACR_NAME).azurecr.io --username $(ACR_NAME) --password $(ACR_PASSWORD)
        displayName: Login to Helm Registry


      - task: HelmDeploy@0
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscription: 'PipelineConnection'
          azureResourceGroup: 'default'
          kubernetesCluster: 'default-bestrong-aks'
          useClusterAdmin: true
          namespace: 'default'
          command: 'upgrade'
          chartType: 'Name'
          chartName: 'oci://devbestrongregistry.azurecr.io/helm'
          releaseName: 'application'
          overrideValues: 'image.tag=$(Build.BuildId)'
          arguments: '--reuse-values'

  - job: Approve
    pool: server
    steps:
      - task: ManualValidation@0
        inputs:
          notifyUsers: 'Promote new version?'
  
  - job: Install_Plugin
    displayName: Install Argo Rollouts
    steps:
      - script: |
          curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64
          chmod +x ./kubectl-argo-rollouts-linux-amd64
          sudo mv ./kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts
          

  - job: Promote
    dependsOn: Approve
    steps:
      - task: HelmDeploy@0
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscription: 'PipelineConnection'
          azureResourceGroup: 'default'
          kubernetesCluster: 'default-bestrong-aks'
          useClusterAdmin: true
          namespace: 'default'
          command: 'ls'
      - script: |
          kubectl argo rollouts promote application

# - stage: Rollback
#   dependsOn: Promote
#   jobs:
#   - job: Approve
#     pool: server
#     steps:
#       - task: ManualValidation@0
#         inputs:
#           notifyUsers: 'Rollback to older version?'

#   - job: Rollback
#     dependsOn: Approve
#     steps:
#       - script: |
#           kubectl argo rollouts undo application




