# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self


variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'fbed2136-d61b-4f25-8091-48ea362f93e1'
  imageRepository: 'application'
  containerRegistry: 'devbestrongregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  imageTag: $(Build.BuildId)
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: ACRTask@0
      inputs:
        azureSubscription: 'Azure subscription 1(87ed7345-6e20-4565-844b-70b8b682de46)'
        azureContainerRegistry: 'devbestrongregistry'
        containerRepository: 'application'
        contextType: 'Git'
        githubConnection: 'repo'
        repositoryName: 'c45/ASPNETCore-WebAPI-Sample'
        branch: 'main'
        dockerfileOrTaskFile: 'Dockerfile'

