apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.application.service.type }}
